---
- hosts: servers
  remote_user: steve
  become: yes

  tasks:
    - name: get uptime
      raw: uptime
      register: info

    - debug: var=info.stdout_lines

    - name: get OS release
      raw: cat /etc/os-release
      register: info

    - debug: var=info.stdout_lines
     
    - name: get linux info
      raw: uname -a

      register: info

    - debug: var=info.stdout_lines
 
    - name: Interface info
      raw: ifconfig
      register: info

    - debug: var=info.stdout_lines

    - name: UFW status
      raw: ufw status
      register: info

    - debug: var=info.stdout_lines
