---
- name: Install docker
  raw: apt-get install docker.io -y

- name: Install docker compose
  raw: apt-get install docker-compose -y

- name: Install Git
  raw: apt-get install git -y

- name: Clone wp repo
  raw: git clone https://github.com/stevecosner/docker-compose-wp.git

- name: mv to directory
  raw: cp -r docker-compose-wp/. .

- name: Run Docker WP with Docker compose
  raw: docker-compose up